package vip.ablog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public M setDevid(java.lang.String devid) {
		set("devid", devid);
		return (M)this;
	}
	
	public java.lang.String getDevid() {
		return getStr("devid");
	}
	
	public M setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
		return (M)this;
	}
	
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}
	
	public M setVip(java.lang.Integer vip) {
		set("vip", vip);
		return (M)this;
	}
	
	public java.lang.Integer getVip() {
		return getInt("vip");
	}
	
	public M setDtimes(java.lang.Integer dtimes) {
		set("dtimes", dtimes);
		return (M)this;
	}
	
	public java.lang.Integer getDtimes() {
		return getInt("dtimes");
	}
	
	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}
	
}
