package vip.ablog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTemplate<M extends BaseTemplate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}
	
	public M setDurl(java.lang.String durl) {
		set("durl", durl);
		return (M)this;
	}
	
	public java.lang.String getDurl() {
		return getStr("durl");
	}
	
	public M setPurl(java.lang.String purl) {
		set("purl", purl);
		return (M)this;
	}
	
	public java.lang.String getPurl() {
		return getStr("purl");
	}
	
	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}
	
	public M setFree(java.lang.Integer free) {
		set("free", free);
		return (M)this;
	}
	
	public java.lang.Integer getFree() {
		return getInt("free");
	}
	
	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}
	
}
